### PR TITLE
Support tracing

### PR DESCRIPTION
**Pull request by martincostello**
Support collecting traces from Playwright tests.

Inspired by @slang25 🙇

### CODE REVIEW

**Comment by martincostello** [comment]
A stretch would be to support deep-linking traces directly from the test output/build logs https://trace.playwright.dev.

**Comment by martincostello** [comment]
Looks like BrowserStack Automate does not support traces (or there's a bug in the remote support for it in Playwright).

```sh
[xUnit.net 00:01:52.57]     Search_For_DotNet_Core(browserType: "chromium", browserChannel: "msedge") [FAIL]
  Failed Search_For_DotNet_Core(browserType: "chromium", browserChannel: "msedge") [23 s]
  Error Message:
   Microsoft.Playwright.PlaywrightException : save: expected boolean, got undefined
  Stack Trace:
     at Microsoft.Playwright.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args)
   at Microsoft.Playwright.Transport.Channels.BrowserContextChannel.StopChunkAsync(String mode)
   at Microsoft.Playwright.Core.Tracing.DoStopChunkAsync(String filePath)
   at Microsoft.Playwright.Core.Tracing.StopChunkAsync(TracingStopChunkOptions options)
   at Microsoft.Playwright.Core.Tracing.StopAsync(TracingStopOptions options)
   at PlaywrightTests.BrowserFixture.WithPageAsync(Func`2 action, String testName) in /Users/runner/work/dotnet-playwright-tests/dotnet-playwright-tests/PlaywrightTests/BrowserFixture.cs:line 106
   at PlaywrightTests.BrowserFixture.WithPageAsync(Func`2 action, String testName) in /Users/runner/work/dotnet-playwright-tests/dotnet-playwright-tests/PlaywrightTests/BrowserFixture.cs:line 106
   at PlaywrightTests.BrowserFixture.WithPageAsync(Func`2 action, String testName) in /Users/runner/work/dotnet-playwright-tests/dotnet-playwright-tests/PlaywrightTests/BrowserFixture.cs:line 106
   at PlaywrightTests.SearchTests.Search_For_DotNet_Core(String browserType, String browserChannel) in /Users/runner/work/dotnet-playwright-tests/dotnet-playwright-tests/PlaywrightTests/SearchTests.cs:line 38
--- End of stack trace from previous location ---
```

**Comment by martincostello** [comment]
> A future stretch would be to support deep-linking traces directly from the test output/build logs https://trace.playwright.dev.

This won't work in GitHub Actions as-is because the traces will be within another zip archive, so a deep link wouldn't be pointing to a zip with the expected content.

**Comment by slang25** [comment]
It's a shame remote traces doesn't work yet

**Comment by martincostello** [comment]
Agreed - I'm going to dig into the code locally later and see if it's a Playwright bug or a missing BrowserStack feature, as start works it's just that it fails on stop.

**Comment by martincostello** [comment]
Tracing should work once BrowserStack Automate has 1.18.0 available server-side. Currently their latest version is 1.17.2, so a protocol mismatch is causing it to fail.

**Pull request merged**
